# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-21 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelnet',
            name='fc_vector',
        ),
        migrations.RemoveField(
            model_name='modelnet',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='modelnet',
            name='modelnet_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='ModelNetID'),
        ),
    ]
